version: 2
updates:
  - directory: /
    package-ecosystem: npm
    ignore:
      - dependency-name: typescript
        update-types:
          - version-update:semver-major
    groups:
      npm:
        patterns:
          - "*"
    schedule:
      day: thursday
      interval: weekly
  - directory: /
    package-ecosystem: github-actions
    schedule:
      day: thursday
      interval: weekly
